version: '2'

networks:
  snapcast_nw:

volumes:
  snapcast:

services:
  snapserver:
    ports:
      - "1704:1704"
      - "1705:1705"
    restart: always  
    image: vproke/rpi-snapserver:latest
    networks:
      - snapcast_nw
    volumes:
      - snapcast:/tmp

  mopidy:
    image: vproke/rpi-mopidy:latest
    ports:
      - "6600:6600"
      - "6680:6680"
    volumes:
      - "/share/Multimedia:/media/music"
    restart: always    
    volumes:
      - snapcast:/tmp
    environment:
      - SPOTIFY_USERNAME
      - SPOTIFY_PASSWORD
      - LASTFM_USERNAME
      - LASTFM_PASSWORD
    entrypoint:
      - "/usr/local/bin/mopidy.sh"
      - "--snapcast"
      
  home-assistant:
    image: homeassistant/armhf-homeassistant:0.65.6
    network_mode: host
    ports:
      - "8123:8123"
      - "1883:1883"
    volumes:
      - /share/Container/homeassistant/config:/config
      - /etc/localtime:/etc/localtime
    restart: always

  hass-configurator:
    image: "causticlab/hass-configurator-docker:arm-0.2.6"
    restart: always
    ports:
      - "3218:3218"
    network_mode: host
    volumes:
      - "/share/Container/homeassistant/configurator-config:/config"
      - "/share/Container/homeassistant/config:/hass-config"