version: '2'

networks:
  snapcast_nw:

volumes:
  snapcast:

services:
  snapserver:
    image: vproke/rpi-snapserver:latest
    networks:
      - snapcast_nw
    volumes:
      - snapcast:/tmp

  mopidy:
    image: vproke/rpi-mopidy:latest
    volumes:
      - snapcast:/tmp
    environment:
      - SPOTIFY_USERNAME
      - SPOTIFY_PASSWORD
      - LASTFM_USERNAME
      - LASTFM_PASSWORD
    entrypoint:
      - "/usr/local/bin/mopidy.sh"
      - "--snapcast"

  home-assistant:
    image: lroguet/rpi-home-assistant:latest
    network_mode: host

#  hass-configurator:
#    image: causticlab/hass-configurator-docker:latest



